FileVersion = 1
Projects = {example = {Path = "."}, GLTF = {Path = "../.."}, SDL3 = {Path = "../../../SDL3"}, json = {Path = "../../../json"}, sead = {Path = "../../../sead"}}

[Workspace]
StartupProject = "example"
