FileVersion = 1
Dependencies = {corlib = "*", json = "*", sead = "*"}

[Project]
Name = "GLTF"
DefaultNamespace = "gLTF"

[[ProjectFolder.Items]]
Type = "IgnoreFolder"
Name = "example"
AutoInclude = true
